### ISSUE TITLE
Automatically create models so that every Player always has an Attendance for each Event

### ISSUE THREAD

**Issue by cmavelis** [cmavelis/team_manager#4]
@adamaviv do you have a good sense of how to do this?  Stackoverflow was pointing me in the direction of signals

**Comment by adamaviv** [comment]
You don't do this with creating new models.

We should discuss what kind of database schema you need for this, and from
that, we can design a set of models to match the schema.

**Comment by cmavelis** [comment]
I think I meant model instances, if that changes things

**Comment by adamaviv** [comment]
Yeah, that will come naturally through a good schema and design.

We should chat a bit more about exactly what are your requirements so we
can design a good schema. Maybe that should be its own issue.
